@baseUrl = http://localhost:{{$dotenv PORT}}/api

# @name GetPosts
GET {{baseUrl}}/post/
###

@postId = {{GetPosts.response.body.0._id}}
@postAuthor = {{GetPosts.response.body.0.author.handle}}

GET {{baseUrl}}/post/{{postId}}
###

GET {{baseUrl}}/user/{{postAuthor}}
###